services:
  - type: web
    name: aml-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aml-db
          property: connectionString
      - key: GROQ_ENABLED
        value: "yes"
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"

databases:
  - name: aml-db
    plan: free
    postgresMajorVersion: "16"
